on:
    push:
        branch:
            - main
    pull_request:

name: Coverage

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.7']

        steps:
            - name: 'Check out the repo'
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Run tests
              run: |
                  pip install pytest
                  pip install pytest-cov
                  pytest tests --doctest-modules --junitxml=.coverage.xml --cov=dicegame | tee .coverage.txt

            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@main
              with:
                  pytest-coverage-path: ./.coverage.txt
                  junitxml-path: ./.coverage.xml
